[features]
seeds = false
[programs.devnet]
gif_portal = "Gj8z2PqD3A5M5J9LkFhi1Jd5ZDaHpentAcAMzUgJQMEk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/barros/.config/solana/id.json"

[scripts]
test = "node tests/gif-portal.js"
